// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXM8GPN69k-uxdsOxEdG0dFlHlY7GyFy4',
    appId: '1:776664567368:web:29dbe08731e7da909a127d',
    messagingSenderId: '776664567368',
    projectId: 'trackbangla-faef2',
    authDomain: 'trackbangla-faef2.firebaseapp.com',
    storageBucket: 'trackbangla-faef2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHvidbno8-bcts8xSCaDSFrio26KJTLY4',
    appId: '1:776664567368:android:55b918dd493320ef9a127d',
    messagingSenderId: '776664567368',
    projectId: 'trackbangla-faef2',
    storageBucket: 'trackbangla-faef2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbgioP8TdIxmfaN-uTekd89SNBu1mzGJk',
    appId: '1:776664567368:ios:2e90c3e97971f1069a127d',
    messagingSenderId: '776664567368',
    projectId: 'trackbangla-faef2',
    storageBucket: 'trackbangla-faef2.appspot.com',
    iosBundleId: 'com.example.trackbangla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbgioP8TdIxmfaN-uTekd89SNBu1mzGJk',
    appId: '1:776664567368:ios:e72c63ff4d0db4c49a127d',
    messagingSenderId: '776664567368',
    projectId: 'trackbangla-faef2',
    storageBucket: 'trackbangla-faef2.appspot.com',
    iosBundleId: 'com.example.trackbangla.RunnerTests',
  );
}
